// https://en.wikipedia.org/wiki/List_of_Greek_mythological_figures

const greekDeities = [
    'Aphrodite',
    'Apollo',
    'Ares',
    'Artemis',
    'Athena',
    'Demeter',
    'Dionysus',
    'Hades',
    'Hephaestus',
    'Hera',
    'Hermes',
    'Hestia',
    'Poseidon',
    'Zeus',
    'Coeus',
    'Crius',
    'Cronus',
    'Hyperion',
    'Iapetus',
    'Mnemosyne',
    'Oceanus',
    'Phoebe',
    'Rhea',
    'Tethys',
    'Theia',
    'Themis',
    'Asteria',
    'Astraeus',
    'Atlas',
    'Aura',
    'Clymene',
    'Dione',
    'Helios',
    'Selene',
    'Eos',
    'Epimetheus',
    'Eurybia',
    'Eurynome',
    'Lelantos',
    'Leto',
    'Menoetius',
    'Metis',
    'Ophion',
    'Pallas',
    'Perses',
    'Prometheus',
    'Styx',
];

export default greekDeities;
